project:
  type: website
  output-dir: docs
website:
  title: "ilovetensor"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ilovetensor
      - icon: twitter
        href: https://twitter.com/rohanshar11
format:
  html:
    theme:
      light: flatly
      dark: cyborg
    css: styles.css



